/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lottoZapSol from "./LottoZap.sol";
export type { lottoZapSol };
import type * as mocks from "./mocks";
export type { mocks };
export type { LottoFactory } from "./LottoFactory";
export type { Raffle } from "./Raffle";
