/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRaffle } from "./IRaffle";
export type { ISwapRouter } from "./ISwapRouter";
export type { IWETH } from "./IWETH";
export type { LottoZap } from "./LottoZap";
