/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface LottoZapInterface extends Interface {
  getFunction(
    nameOrSignature: "i_swapRouter" | "i_weth" | "swapAndEnter"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "i_swapRouter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "i_weth", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swapAndEnter",
    values: [AddressLike, BigNumberish, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "i_swapRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "i_weth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapAndEnter",
    data: BytesLike
  ): Result;
}

export interface LottoZap extends BaseContract {
  connect(runner?: ContractRunner | null): LottoZap;
  waitForDeployment(): Promise<this>;

  interface: LottoZapInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  i_swapRouter: TypedContractMethod<[], [string], "view">;

  i_weth: TypedContractMethod<[], [string], "view">;

  swapAndEnter: TypedContractMethod<
    [
      tokenIn: AddressLike,
      amountInMax: BigNumberish,
      raffle: AddressLike,
      fee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "i_swapRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "i_weth"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "swapAndEnter"
  ): TypedContractMethod<
    [
      tokenIn: AddressLike,
      amountInMax: BigNumberish,
      raffle: AddressLike,
      fee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
