/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRaffle,
  IRaffleInterface,
} from "../../../contracts/LottoZap.sol/IRaffle";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "player",
        type: "address",
      },
    ],
    name: "buyTicketFor",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "getEntranceFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRaffle__factory {
  static readonly abi = _abi;
  static createInterface(): IRaffleInterface {
    return new Interface(_abi) as IRaffleInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IRaffle {
    return new Contract(address, _abi, runner) as unknown as IRaffle;
  }
}
