/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILottoFactory,
  ILottoFactoryInterface,
} from "../../../contracts/Raffle.sol/ILottoFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "winner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "ticketPrice",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxTickets",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "duration",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "rewardToken",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "numWinners",
        type: "uint32",
      },
    ],
    name: "onRaffleEnded",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILottoFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ILottoFactoryInterface {
    return new Interface(_abi) as ILottoFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILottoFactory {
    return new Contract(address, _abi, runner) as unknown as ILottoFactory;
  }
}
