/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ILottoFactory__factory } from "./ILottoFactory__factory";
export { Raffle__factory } from "./Raffle__factory";
